"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# CORE SETTINGS
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

if not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]

# Environment
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')


# APPLICATION DEFINITION

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_ratelimit',
    'defender',
    # Local apps
    'apps.core',
    'apps.users',
    'apps.tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'defender.middleware.FailedLoginMiddleware',
]

ROOT_URLCONF = 'task_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_manager.wsgi.application'


# AUTHENTICATION

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': int(os.getenv('PASSWORD_MIN_LENGTH', '8')),
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# DATABASE CONFIGURATION

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        'ATOMIC_REQUESTS': os.getenv('DB_ATOMIC_REQUESTS', 'True').lower() in ('true', '1', 't'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '10')),
            'read_timeout': int(os.getenv('DB_READ_TIMEOUT', '30')),
            'write_timeout': int(os.getenv('DB_WRITE_TIMEOUT', '30')),
        },
    }
}


# INTERNATIONALIZATION

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')
USE_I18N = True
USE_TZ = True


# STATIC & MEDIA FILES

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.path.join(BASE_DIR, os.getenv('STATIC_ROOT', 'staticfiles'))

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, os.getenv('MEDIA_ROOT', 'media'))

# File Upload Settings
MAX_UPLOAD_SIZE = int(os.getenv('MAX_UPLOAD_SIZE', '5242880'))  # 5MB default
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE


# SECURITY SETTINGS

if not DEBUG:
    # SSL/HTTPS
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 't')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')


# CORS CONFIGURATION

CORS_ALLOWED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') 
    if origin.strip()
]

CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() in ('true', '1', 't')

CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') 
    if origin.strip()
]


# REST FRAMEWORK CONFIGURATION

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('DRF_PAGE_SIZE', '20')),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'apps.core.exception_handler.custom_exception_handler',
    'DATE_INPUT_FORMATS': ['%Y-%m-%d'],
    'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': os.getenv('DRF_USER_THROTTLE_RATE', '1000/hour'),
        'anon': os.getenv('DRF_ANON_THROTTLE_RATE', '100/hour'),
    },
}


# JWT CONFIGURATION

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '1'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() in ('true', '1', 't'),
    'BLACKLIST_AFTER_ROTATION': os.getenv('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() in ('true', '1', 't'),
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# API DOCUMENTATION (DRF Spectacular)

SPECTACULAR_SETTINGS = {
    'TITLE': os.getenv('API_TITLE', 'Task Manager API'),
    'DESCRIPTION': os.getenv('API_DESCRIPTION', 'API documentation for Task Manager application'),
    'VERSION': os.getenv('API_VERSION', '1.0.0'),
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api',
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


# CACHING WITH REDIS

USE_REDIS = os.getenv('USE_REDIS', 'True').lower() in ('true', '1', 't')

if USE_REDIS:
    REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
    REDIS_PORT = os.getenv('REDIS_PORT', '6379')
    REDIS_DB = os.getenv('REDIS_DB', '1')
    REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')
    
    # Construct Redis URL
    if REDIS_PASSWORD:
        REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    else:
        REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PASSWORD': REDIS_PASSWORD,
                'SOCKET_CONNECT_TIMEOUT': int(os.getenv('REDIS_CONNECT_TIMEOUT', '5')),
                'SOCKET_TIMEOUT': int(os.getenv('REDIS_SOCKET_TIMEOUT', '5')),
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS', '50'))
                }
            },
            'KEY_PREFIX': os.getenv('REDIS_KEY_PREFIX', 'taskmanager'),
            'TIMEOUT': int(os.getenv('CACHE_TIMEOUT', '300')),
        }
    }
    # Use Redis for sessions
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# RATE LIMITING CONFIGURATION

RATELIMIT_ENABLE = os.getenv('RATELIMIT_ENABLE', 'True').lower() in ('true', '1', 't')
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'apps.users.views.rate_limited_view'


# DJANGO DEFENDER (Brute Force Protection)

DEFENDER_LOGIN_FAILURE_LIMIT = int(os.getenv('DEFENDER_FAILURE_LIMIT', '5'))
DEFENDER_COOLOFF_TIME = int(os.getenv('DEFENDER_COOLOFF_TIME', '300'))
DEFENDER_LOCKOUT_TEMPLATE = None  # Use JSON response
DEFENDER_STORE_ACCESS_ATTEMPTS = True
DEFENDER_USE_CELERY = False
DEFENDER_ACCESS_ATTEMPT_EXPIRATION = int(os.getenv('DEFENDER_ATTEMPT_EXPIRATION', '24'))

# Defender Redis configuration
if USE_REDIS:
    DEFENDER_REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
    DEFENDER_REDIS_PORT = os.getenv('REDIS_PORT', '6379')
    DEFENDER_REDIS_DB = os.getenv('DEFENDER_REDIS_DB', '0')
    DEFENDER_REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')
    
    if DEFENDER_REDIS_PASSWORD:
        DEFENDER_REDIS_URL = f"redis://:{DEFENDER_REDIS_PASSWORD}@{DEFENDER_REDIS_HOST}:{DEFENDER_REDIS_PORT}/{DEFENDER_REDIS_DB}"
    else:
        DEFENDER_REDIS_URL = f"redis://{DEFENDER_REDIS_HOST}:{DEFENDER_REDIS_PORT}/{DEFENDER_REDIS_DB}"


# LOGGING CONFIGURATION

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': os.getenv('LOG_LEVEL_CONSOLE', 'DEBUG' if DEBUG else 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': os.getenv('LOG_LEVEL_FILE', 'INFO'),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': int(os.getenv('LOG_MAX_BYTES', str(1024 * 1024 * 10))),  # 10MB
            'backupCount': int(os.getenv('LOG_BACKUP_COUNT', '5')),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': os.getenv('LOG_LEVEL_SECURITY', 'WARNING'),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'maxBytes': int(os.getenv('LOG_MAX_BYTES', str(1024 * 1024 * 10))),
            'backupCount': int(os.getenv('LOG_BACKUP_COUNT', '5')),
            'formatter': 'verbose',
        },
        'user_activity_file': {
            'level': os.getenv('LOG_LEVEL_USER_ACTIVITY', 'INFO'),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'user_activity.log'),
            'maxBytes': int(os.getenv('LOG_MAX_BYTES', str(1024 * 1024 * 10))),
            'backupCount': int(os.getenv('LOG_BACKUP_COUNT', '5')),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL_DJANGO', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': os.getenv('LOG_LEVEL_REQUEST', 'ERROR'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': os.getenv('LOG_LEVEL_SECURITY', 'WARNING'),
            'propagate': False,
        },
        'apps.users': {
            'handlers': ['console', 'user_activity_file'],
            'level': os.getenv('LOG_LEVEL_USERS', 'INFO'),
            'propagate': False,
        },
        'defender': {
            'handlers': ['security_file'],
            'level': os.getenv('LOG_LEVEL_DEFENDER', 'WARNING'),
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL_ROOT', 'INFO'),
    },
}


# APPLICATION SETTINGS

SITE_NAME = os.getenv('SITE_NAME', 'Task Manager')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')


# SENTRY (Error Monitoring)

SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
        environment=ENVIRONMENT,
        release=os.getenv('RELEASE_VERSION', 'unknown'),
    )


# ADMIN CONFIGURATION

ADMINS = [
    ('Admin', os.getenv('ADMIN_EMAIL', 'jamespmurithi@gmail.com')),
]
MANAGERS = ADMINS


# MISCELLANEOUS

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'